//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShopProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLDETAIL
    {
        public string BILL_ID { get; set; }
        public string CAKE_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual CAKE CAKE { get; set; }
    }
}
