//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShopProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAKE()
        {
            this.BILLDETAILs = new HashSet<BILLDETAIL>();
            this.CAKE_IMAGES = new HashSet<CAKE_IMAGES>();
        }
    
        public string CAKE_ID { get; set; }
        public string TYPE_ID { get; set; }
        public string CAKE_NAME { get; set; }
        public string CAKE_DESCRIPTION { get; set; }
        public Nullable<decimal> CAKE_PRICE { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<bool> EXIST_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLDETAIL> BILLDETAILs { get; set; }
        public virtual TYPE TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAKE_IMAGES> CAKE_IMAGES { get; set; }
    }
}
